# Generated by Django 4.2.1 on 2023-05-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='img',
        ),
    ]
